---
- name: Start the Telegraf service
  ansible.builtin.service:
    name: telegraf
    state: started
    enabled: true
  # Only care to check the status if the state changed to 'started'
  notify:
    - "pause"
    - "check status"
    - "assert running"
  become: true
